version: "3.9"

services:

  mysql:

    image: mysql:8.4

    container_name: task-dashboard-mysql

    restart: unless-stopped

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:

      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

      interval: 10s

      retries: 10

    networks:
      - devops-network

  app:

    build:
      context: ..

      dockerfile: Dockerfile

    container_name: task-dashboard-app

    depends_on:

      mysql:

        condition: service_healthy

    ports:

      - "8080:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_dashboard

      SPRING_DATASOURCE_USERNAME: taskuser

      SPRING_DATASOURCE_PASSWORD: task123

    networks:

      - devops-network

volumes:

  mysql-data:

networks:

  devops-network: