name: CI Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Trivy filesystem scan
              uses: aquasecurity/trivy-action@0.35.0  
              with:
                scan-type: fs
                scan-ref: .
                format: table
                severity: HIGH,CRITICAL
                exit-code: '0'

            - name: Build Docker Image
              run: |
                docker build \
                -t ${{secrets.DOCKERHUB_USERNAME}}/task-dashboard:latest \
                -t ${{secrets.DOCKERHUB_USERNAME}}/task-dashboard:${{github.sha}} \
                .

            - name: Login to Docker hub
              uses: docker/login-active@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}
            
            - name: Push latest and SHA tagged Image
              run: |
                docker push ${{secrets.DOCKERHUB_USERNAME}}/task-dashboard:${{github.sha}}

            - name: Trivy Image Scan
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: task-dashboard:latest
                format: table
                severity: HIGH,CRITICAL
                exit-code: '0'
